### ISSUE TITLE
bspatch: corrupt patch or bzstream ended (3)

### ISSUE THREAD

**Issue by xLivan** [gabstv/go-bsdiff#2] opened 2019-03-19 17:07 UTC
Hi. I tried generating patch for some .dll file (47.2 MB -> 57.8 MB).
Patch is generated successfully, but bspatch is giving error:
`bspatch: corrupt patch or bzstream ended (3):`.
I also tried applying this patch (generated with go-bsdiff) with original bspatch. File was patched successfully and target and patched files are identical.
So, I think, there is an error in bspatch?
I can provide files, if you need it.

**Comment by gabstv** [comment] 2019-03-19 19:48
Hello. It's possible that there is an error on bspatch. I created some tests but they didn't cover everything apparently. I will look into it tonight.

**Comment by gabstv** [comment] 2019-03-20 15:19
It was an issue related to the bzip2 library (bzip2 lib internal buffer cap). Fixed in 1.0.4.

**Comment by xLivan** [comment] 2019-03-20 23:16
Now there is another error on the same files: `bspatch: corrupt patch or bzstream ended:`.

**Comment by gabstv** [comment] 2019-03-21 11:18
Can I have a file example to test it? I couldn't reproduce the error.

**Comment by Livan-pro** [comment] 2019-03-21 12:37
Yes, I uploaded files here: https://file.io/SU8dij

**Comment by gabstv** [comment] 2019-03-21 12:58
I just pushed a hotfix (1.0.5) and ran bsdiff + bspatch on the DLLs:

``` 
➜   ls
chrome_new.dll chrome_old.dll
➜  tmp git:(develop) : go run ../cmd/bsdiff/main.go chrome_old.dll chrome_new.dll chrome_patch
➜  tmp git:(develop) : go run ../cmd/bspatch/main.go chrome_old.dll chrome_new2.dll chrome_patch
➜  tmp git:(develop) : ls -al        
total 384136
drwx------@  6 gabs  staff       192 Mar 21 09:50 .
drwxr-xr-x  16 gabs  staff       512 Mar 21 09:41 ..
-rwxr-xr-x@  1 gabs  staff  60694512 Mar 11 10:08 chrome_new.dll
-rw-r--r--   1 gabs  staff  60694512 Mar 21 09:50 chrome_new2.dll
-rwxr-xr-x@  1 gabs  staff  49559552 Nov 26 01:09 chrome_old.dll
-rw-r--r--   1 gabs  staff  25723455 Mar 21 09:46 chrome_patch
➜  tmp git:(develop) : diff chrome_new.dll chrome_new2.dll
➜  tmp git:(develop) : 
```

It seems to be working fine.

**Comment by Livan-pro** [comment] 2019-03-21 13:13
Yes, thank you!

**Closed by Livan-pro** 2019-03-21 13:13 UTC
